[package]
name = "stitch-rust-sdk"
version = "0.1.0"
authors = ["jsflax <jsflax@gmail.com>"]

[dependencies]
futures = "0.1"
futures-cpupool = "0.1"

curl = "0.4.8"

# json
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"
